name = 'Jane'
print(f'Good morning, {name}!')
import time
print(time.asctime())
print(1, 2, 3, 'a', 'b', sep=',')
print('a', 'b', 'c', 'd', 'e', sep='')
print(1, 2, 'a', 'b', sep=',', end=' <- \n')
print('a', 'b', end='', sep=',')
print('c', 'd', sep=',')
print()
print("What's your name?")
name = input()
print(f'Good Morning, {name}!')
last_name = input("What's your last name?\n")
print(f'Good Morning, {name} {last_name}!')
print()
number1 = input('Enter the first number: ')
number2 = input('Enter the second number: ')
sum = float(number1) + float(number2)
print()
print(f'The numbers {number1} and {number2}'
      f' add to {sum}.')
print()
print('Input/Output Exercises')
print('#1 & 2')
first_name = input("What's your first name?\n")
last_name = input("What's you last name? \n")
print(f'Hello, {first_name} {last_name}!')
print()
print('#3')
age = int(input('How old are you? '))
print()
print(f'You are {age} years old.')
print(f'In 10 years, you will be {age + 10} years old.')
print(f'In 20 years, you will be {age + 20} years old.')
print(f'In 30 years, you will be {age + 30} years old.')
print(f'In 40 years, you will be {age + 40} years old.')